name: Laravel Authentication Image Build and Push

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          context: .
          image: engyahmed3/laravel-authentication
          file: ./Dockerfile
          push: true
          username: "${{ secrets.HUB_USERNAME }}"
          password: "${{ secrets.HUB_PASSWORD }}"
          tags: latest
